JobChannalizedLearning/jcl/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from ApiApplication.views import FieldApiView as api_application_views, show_plot

urlpatterns = [
                  path('', include('user_account.urls')),
                  path('content/', include('website_content.urls')),
                  path('admin/', admin.site.urls),

                  # password Reset
                  path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                      template_name='registration/password_change_done.html'), name='password_change_done'),
                  path('password_change/',
                       auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
                       name='password_change'),
                  path('password_reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(),
                       name='password_reset'),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

                  # quiz section
                  path('quiz/', include('quiz.urls', namespace='quiz')),
                  path('dashboard/', show_plot, name='dashboard'),
                  re_path(r'fields', api_application_views.as_view()),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

JobChannalizedLearning/quiz/urls.py
from django.urls import path
from .views import (
    Quiz_list_view,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    quizzes,
    add_quiz,
    update_quiz,
    delete_quiz,
    question_list,
    add_question,
    delete_question,
    update_question,
)

app_name = 'quiz'

urlpatterns = [
    path('quizzes/<str:slug>/', quizzes, name='quizzes'),
    path('add_quiz/<str:slug>/', add_quiz, name='add_quiz'),
    path('update-quiz/<int:quiz_id>/<str:slug>/', update_quiz, name='update_quiz'),
    path('delete-quiz/<int:quiz_id>/<str:slug>/', delete_quiz, name='delete_quiz'),
    path('<str:slug>', Quiz_list_view.as_view(), name='main-view'),
    path('<str:slug>/<int:pk>/', quiz_view, name='quiz-view'),
    path('<str:slug>/<int:pk>/save/', save_quiz_view, name='save-view'),
    path('<str:slug>/<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('update/question-list/<int:quiz_id>/', question_list, name='question_list'),
    path('update/add-question/<int:quiz_id>/', add_question, name='add_question'),
    path('update/delete-question/<int:question_id>/', delete_question, name='delete_question'),
    path('update/update-question/<int:question_id>/', update_question, name='update_question'),
]

JobChannalizedLearning/quiz/models.py
from django.db import models
from course.models import Course
import random

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

JobChannalizedLearning/quiz/forms.py
# forms.py
from questions.models import Question, Answer
from django import forms
from .models import Quiz, DIFF_CHOICES

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'number_of_questions', 'time', 'required_score_to_pass', 'difficulty']
        widgets = {
            'difficulty': forms.Select(choices=DIFF_CHOICES)
        }
class QuizUploadForm(forms.Form):
    json_file = forms.FileField(label='Upload JSON File')

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']

AnswerFormSet = forms.inlineformset_factory(
    Question,
    Answer,
    fields=('text', 'correct'),
    can_delete=False,
    min_num=1,
    validate_min=True,
)

JobChannalizedLearning/quiz/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Quiz
from django.views import View
from django.http import HttpResponseNotAllowed, JsonResponse
from questions.models import Question, Answer
from results.models import Result
from .forms import QuizForm, QuestionForm, AnswerFormSet, QuizUploadForm
from django.shortcuts import get_object_or_404
from django.forms import inlineformset_factory
from django.db.models import OuterRef, Subquery
from django.contrib.auth.decorators import login_required
import json

@login_required
def question_list(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    questions = quiz.question_set.all()
    form = QuizUploadForm()
    if request.POST:
        form = QuizUploadForm(request.POST, request.FILES)
        if form.is_valid():
            json_file = form.cleaned_data['json_file']
            json_data = json.load(json_file)
            for question in json_data:
                question_instance = Question(
                    text=question['text'],
                    quiz=quiz,
                )
                question_instance.save()
                for answer in question['answers']:
                    answer_instance = Answer(
                        text=answer['text'],
                        correct=answer['correct'],
                        question=question_instance,
                    )
                    answer_instance.save()
        return redirect('quiz:question_list', quiz_id=quiz.id)
    return render(request, 'quiz/question_list.html', {'quiz': quiz, 'questions': questions, 'form': form})

@login_required
def add_question(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    if request.method == 'POST':
        print(request.POST)
        question_form = QuestionForm(request.POST)
        answer_formset = AnswerFormSet(request.POST)
        if question_form.is_valid() and answer_formset.is_valid():
            question = question_form.save(commit=False)
            question.quiz = quiz
            question.save()
            answer_formset.instance = question
            answer_formset.save()
            return redirect('quiz:question_list', quiz_id=quiz.id)
    else:
        question_form = QuestionForm()
        answer_formset = AnswerFormSet()
    return render(request, 'quiz/add_question.html', {'quiz': quiz, 'question_form': question_form, 'answer_formset': answer_formset})

@login_required
def delete_question(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    if request.method == 'POST':
        question.delete()
        return redirect('quiz:question_list', quiz_id=question.quiz.id)
    else:
        return HttpResponseNotAllowed(['POST'])


@login_required
def update_question(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    AnswerFormSet = inlineformset_factory(Question, Answer, fields=('text', 'correct'), extra=0)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('quiz:question_list', quiz_id=question.quiz.id)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)
    return render(request, 'quiz/update_question.html', {'form': form, 'formset': formset})

@login_required
def delete_answer(request, answer_id):
    answer = get_object_or_404(Answer, id=answer_id)
    if request.method == 'POST':
        answer.delete()
        return redirect('quiz:update_question', question_id=answer.question.id)
    else:
        return HttpResponseNotAllowed(['POST'])

@login_required
def quizzes(request, slug):
    quizzes = Quiz.objects.filter(topic=slug)
    return render(request, 'quiz/quizzes.html', {'quizzes': quizzes, 'slug': slug})

@login_required
def add_quiz(request, slug):
    if request.method == 'POST':
        form = QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.topic = slug
            form.save()
            return redirect('quiz:quizzes', slug=slug)
    else:
        form = QuizForm()
    return render(request, 'quiz/add_quiz.html', {'form': form})

@login_required
def update_quiz(request, quiz_id, slug):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    if request.method == 'POST':
        form = QuizForm(request.POST, instance=quiz)
        if form.is_valid():
            form.save()
            return redirect('quiz:quizzes', slug=slug)
    else:
        form = QuizForm(instance=quiz)
    return render(request, 'quiz/update_quiz.html', {'form': form, 'quiz': quiz, 'slug': slug})

@login_required
def delete_quiz(request, quiz_id, slug):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    if request.method == 'POST':
        quiz.delete()
        return redirect('quiz:quizzes', slug=slug)
    else:
        return HttpResponseNotAllowed(['POST'])

class Quiz_list_view(View):
    def get(self,request,slug):
        if not request.user.is_authenticated:
            return redirect('user_account:login_first')
        context={}
        score_subquery = Result.objects.filter(quiz=OuterRef('pk')).values('quiz').order_by('-score').values('score')[
                         :1]
        context['object_list'] = Quiz.objects.filter(topic=slug).annotate(score=Subquery(score_subquery))
        return render(request,'quiz/main.html',context)


@login_required
def quiz_view(request, slug, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quiz/quiz.html', {'obj': quiz, 'slug':slug})

@login_required
def quiz_data_view(request,slug,pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

@login_required
def save_quiz_view(request,slug, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

JobChannalizedLearning/quiz/templates/quiz/add_question.html
<!-- add_question.html -->
{% extends "root.html" %} {% block content %}
<div class="container mt-4 bg-white p-5">
  <h1>Add New Question</h1>
  <form method="post" id="addQuestionForm">
    {% csrf_token %}
    <div class="mb-3">
      <label for="{{ question_form.text.id_for_label }}" class="form-label"
        >Question:</label
      >
      {{ question_form.text }}
    </div>
    {{ answer_formset.management_form }}
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="align-middle">Answer</th>
            <th class="align-middle">Correct</th>
          </tr>
        </thead>
        <tbody>
          {% for form in answer_formset.forms %}
          <tr>
            <td>{{ form.text }}</td>
            <td class="align-middle">
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="radio"
                  name="{{ form.correct.name }}"
                  id="{{ form.correct.id_for_label }}"
                  value="true"
                  {%
                  if
                  form.correct.value
                  %}checked{%
                  endif
                  %}
                />
                <label
                  class="form-check-label"
                  for="{{ form.correct.id_for_label }}"
                  >Correct</label
                >
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Save</button>
  </form>
</div>

{% endblock content %}

JobChannalizedLearning/quiz/templates/quiz/add_quiz.html
<!-- add_quiz.html -->

{% extends "root.html" %} {% block content %}
<style>
  body {
    font-family: Arial, sans-serif;
    background-color: #f8f9fa;
  }

  h1 {
    font-size: 2rem;
    font-weight: bold;
    margin-bottom: 20px;
    text-align: center;
    color: #007bff;
  }

  form {
    display: flex;
    flex-direction: column;
    align-items: left;
  }

  label {
    font-weight: bold;
    margin-bottom: 10px;
    color: #333;
  }

  input,
  select {
    padding: 10px;
    border: 1px solid #ced4da;
    border-radius: 4px;
    margin-bottom: 15px;
    transition: border-color 0.2s ease-in-out;
  }

  input:focus,
  select:focus {
    outline: none;
    border-color: #007bff;
  }

  .helptext {
    font-size: 0.875rem;
    color: #6c757d;
  }

  button[type="submit"] {
    padding: 8px 20px;
    width: 200px;
    align-items: center;
    font-size: 1rem;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.2s ease-in-out;
  }

  button[type="submit"]:hover {
    background-color: #0056b3;
  }
</style>
<div>
  <h1>Add Quiz</h1>
</div>
<div class="form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
</div>
{% endblock content %}

JobChannalizedLearning/quiz/templates/quiz/main.html
{% extends "root.html" %} {% block content %} {% load static %}

<!-- Modal -->
<div
  class="modal fade"
  id="quizStartModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">
          back
        </button>
        <button type="button" id="start-button" class="btn btn-success">
          yes
        </button>
      </div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="h1">Quiz List</div>

  {% for obj in object_list %}
  <button
    class="btn btn-primary btn-lg modal-button mb-3"
    data-pk="{{obj.pk}}"
    data-quiz="{{obj.name}}"
    data-questions="{{obj.number_of_questions}}"
    data-difficulty="{{obj.difficulty}}"
    data-time="{{obj.time}}"
    data-pass="{{obj.required_score_to_pass}}"
    data-score="{{ obj.score }}"
    data-bs-toggle="modal"
    data-bs-target="#quizStartModal"
  >
    {{obj.name|slice:"3:"}}
  </button>
  {% endfor %}
</div>

<script src="{% static 'quiz/main.js'  %}"></script>
{% endblock content %}

JobChannalizedLearning/quiz/templates/quiz/question_list.html
<!-- question_list.html -->
{% extends "root.html" %} {% block content %}
<style>
  html,
  body {
    margin-top: 35px;
    margin-bottom: 10%;
  }
</style>

<div class="container mt-4">
  <h1>Questions for {{ quiz.name }}</h1>
  <a href="{% url 'quiz:add_question' quiz.id %}" class="btn btn-primary my-3"
    >Add New Question</a
  >
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form }}
    <button type="submit" class="btn btn-primary mt-3">Upload</button>
  </form>
  <div class="list-group mt-4">
    <div class="list-group-item">
      {% if questions %}
      <div class="list-group list-group-flush">
        {% for question in questions %}
        <div class="list-group-item">
          <p class="fs-5">{{ question.text }}</p>
          {% if question.get_answers %}
          <ul class="list-group list-group-flush">
            {% for answer in question.get_answers %}
            <li
              class="list-group-item d-flex justify-content-between align-items-center"
            >
              {{ answer.text }} {% if answer.correct %}
              <span class="badge bg-success">Correct</span>
              {% endif %}
            </li>
            {% endfor %}
          </ul>
          {% else %}
          <p class="text-muted">No answers added for this question.</p>
          {% endif %}
          <div class="mt-3 d-flex justify-content-end">
            <form
              method="post"
              action="{% url 'quiz:delete_question' question.id %}"
              class="d-inline"
            >
              {% csrf_token %}
              <button type="submit" class="btn btn-danger me-2">Delete</button>
            </form>
            <a
              href="{% url 'quiz:update_question' question.id %}"
              class="btn btn-secondary"
              >Update</a
            >
          </div>
        </div>
        {% endfor %}
      </div>
      {% else %}
      <p class="text-muted">No questions added yet.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

JobChannalizedLearning/quiz/templates/quiz/quiz.html
{% extends "root.html" %} {% load static %} {% block content %}
<title>{{obj.name}}</title>
<div class="bg-white p-5">
  <div class="row">
    <div class="col">
      <b>{{obj.name}}</b>
      <p>Attempt Quiz</p>
      <p>score to pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
  </div>

  <a href="{% url 'quiz:main-view' slug=slug %} " class="btn btn-danger"
    >go back</a
  >

  <form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">save</button>
  </form>
  <div id="score-box"></div>
  <div id="result-box"></div>
</div>

<script src="{% static 'quiz/quiz.js' %}"></script>
{% endblock content %}

JobChannalizedLearning/quiz/templates/quiz/quizzes.html
<!-- quizzes.html -->
<style>
  body {
    font-family: Arial, sans-serif;
  }

  .quiz-link {
    color: #007bff;
  }

  .quiz-link:hover {
    text-decoration: underline;
  }
</style>
{% extends "root.html" %} {% block content %}
<div class="container py-4">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <h1 class="mb-4">Quiz Manager</h1>
      <a href="{% url 'quiz:add_quiz' slug=slug %}" class="btn btn-primary"
        >Add New Quiz</a
      >
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-8 offset-md-2">
      <h2 class="mb-4">Previous Quizzes</h2>
      <div class="list-group">
        {% for quiz in quizzes %}
        <a
          href="{% url 'quiz:update_quiz' quiz_id=quiz.id slug=slug %}"
          class="list-group-item list-group-item-action quiz-link"
          >{{ quiz.name|slice:"3:" }}</a
        >
        {% empty %}
        <div class="list-group-item">No quizzes found.</div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<!-- Include Bootstrap JS library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>

{% endblock content %}

JobChannalizedLearning/quiz/templates/quiz/update_question.html
<!-- update_question.html -->
{% extends "root.html" %}
{% block content %}
    <h1>Update Question</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        {% for answer_form in formset %}
            {{ answer_form.as_table }}
        {% endfor %}
        <button type="submit">Save</button>
    </form>
{% endblock content %}

JobChannalizedLearning/quiz/templates/quiz/update_quiz.html
<!-- update_quiz.html -->
{% extends "root.html" %} {% block content %}

<style>
  body {
    font-family: Arial, sans-serif;
    line-height: 1;
    margin: 0;
    padding: 0;
  }

  /* Center the content on the page */
  .quiz-form {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-bottom: 60px;
  }

  h1 {
    color: #333;
  }

  .form-container {
    display: flex;
    flex: column;
    justify-content: space-evenly;
  }

  form {
    background-color: #fff;
    padding: 10px;
    border-radius: 5px;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
    width: 400px;

    max-width: 100%;
  }

  form p {
    margin-bottom: 15px;
  }

  label {
    font-weight: bold;
    display: block;
  }

  input,
  select {
    width: 100%;
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 5px;
    font-size: 16px;
    margin-top: 5px;
  }

  .helptext {
    font-size: 12px;
    color: #777;
  }

  button {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 10px;
    border-radius: 5px;
    cursor: pointer;
    font-size: 16px;
  }

  button:hover {
    background-color: #0056b3;
  }

  view-question {
    color: #007bff;
    text-decoration: none;
    font-size: 16px;
  }

  view-question:hover {
    text-decoration: underline;
  }

  /* Additional style for the Delete Quiz button */
  form:last-child {
    margin-top: 20px;
  }
  @media (max-width: 600px) {
    /* Adjust the form width for smaller screens */
    form {
      width: 90%;
    }
  }

  @media (max-width: 400px) {
    /* Further adjustments for smaller screens */
    h1 {
      font-size: 24px;
    }

    /* Reduce padding and font size for smaller screens */
    form,
    form p {
      padding: 5px;
    }

    label {
      font-size: 14px;
    }

    input,
    select {
      font-size: 14px;
    }

    .helptext {
      font-size: 10px;
    }

    button {
      font-size: 14px;
      padding: 8px 10px;
    }

    a {
      font-size: 14px;
    }
  }
</style>
<div class="form-container">
  <div class="quiz-form">
    <h1>Update Quiz</h1>

    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Save</button>
    </form>
    <div>
      <form method="post" action="{% url 'quiz:delete_quiz' quiz.id slug %}">
        {% csrf_token %}
        <button type="submit">Delete Quiz</button>
        <div class="view-question mt-2">
          <a href="{% url 'quiz:question_list' quiz.id  %}">View Questions</a>
          {% endblock content %}
        </div>
      </form>
    </div>
  </div>
</div>