JobChannalizedLearning/course/urls.py
# course.urls.py
from django.urls import path
from .views import COURSES, course_detail, filtered_content


app_name = 'course'

urlpatterns = [
    # Updated name from 'Courses' to 'course_list'
    path('', COURSES, name='course_list'),
    path('<str:name>/', course_detail, name='course_detail'),
    path('<str:name>/<str:slug>/', filtered_content, name='filtered_content'),

]

JobChannalizedLearning/jcl/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from ApiApplication.views import FieldApiView as api_application_views, show_plot

urlpatterns = [
                  path('', include('user_account.urls')),
                  path('content/', include('website_content.urls')),
                  path('admin/', admin.site.urls),

                  # password Reset
                  path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                      template_name='registration/password_change_done.html'), name='password_change_done'),
                  path('password_change/',
                       auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
                       name='password_change'),
                  path('password_reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(),
                       name='password_reset'),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

                  # quiz section
                  path('quiz/', include('quiz.urls', namespace='quiz')),
                  path('dashboard/', show_plot, name='dashboard'),
                  re_path(r'fields', api_application_views.as_view()),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

JobChannalizedLearning/quiz/urls.py
from django.urls import path
from .views import (
    Quiz_list_view,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    quizzes,
    add_quiz,
    update_quiz,
    delete_quiz,
    question_list,
    add_question,
    delete_question,
    update_question,
)

app_name = 'quiz'

urlpatterns = [
    path('quizzes/<str:slug>/', quizzes, name='quizzes'),
    path('add_quiz/<str:slug>/', add_quiz, name='add_quiz'),
    path('update-quiz/<int:quiz_id>/<str:slug>/', update_quiz, name='update_quiz'),
    path('delete-quiz/<int:quiz_id>/<str:slug>/', delete_quiz, name='delete_quiz'),
    path('<str:slug>', Quiz_list_view.as_view(), name='main-view'),
    path('<str:slug>/<int:pk>/', quiz_view, name='quiz-view'),
    path('<str:slug>/<int:pk>/save/', save_quiz_view, name='save-view'),
    path('<str:slug>/<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('update/question-list/<int:quiz_id>/', question_list, name='question_list'),
    path('update/add-question/<int:quiz_id>/', add_question, name='add_question'),
    path('update/delete-question/<int:question_id>/', delete_question, name='delete_question'),
    path('update/update-question/<int:question_id>/', update_question, name='update_question'),
]

JobChannalizedLearning/website_content/urls.py
from django.urls import path, re_path
from .views import home_view, access_grades, course_view, course_detail, filtered_content, plan_details, pay, handle_transaction
from . import views


app_name = 'website_content'
urlpatterns = [
    path('home/', home_view, name='home'),
    path('home/<str:name>/', course_detail, name='course_detail'),
    path('home/<str:name>/<str:slug>/',
         filtered_content, name='filtered_content'),
    path('plan/', plan_details, name='plan_details'),
    path('pay/<str:price>/', pay, name='pay'),
    path('handle-transaction/<str:price>/',
         handle_transaction, name='handle_transaction'),
    path('access_grades/', access_grades, name='access_grades'),
    path('course/<slug:slug>/', course_view, name='course_view'),
]

JobChannalizedLearning/course/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Catogaries(models.Model):
    name = models.CharField(max_length=200, null=True)
    category_image = models.ImageField(upload_to="course/", blank=True)

    def __str__(self):
        return(self.name)


class Course(models.Model):
    STATUS = (
        ('PUBLISH', 'PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )

    featured_image = models.ImageField(upload_to="featured_img/", blank=True)
    video_file = models.FileField(upload_to='videos/', null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    category = models.ForeignKey(Catogaries, on_delete=models.DO_NOTHING)
    description = models.TextField()
    zip_file = models.FileField(
        upload_to='zip_folders/', null=True, blank=True, default=None)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=100, null=True)
    author = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title


User = get_user_model()


class CourseView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    view = models.IntegerField(default=1)
    viewed_at = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"{self.user.username} viewed {self.course.title}"

JobChannalizedLearning/course/forms.py
from django import forms
from course.models import Catogaries, Course

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Catogaries
        fields = ['name', 'category_image']

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['featured_image', 'video_file', 'zip_file','title', 'description', 'status']

# class ZipUploadForm(forms.Form):
#     zip_file = forms.FileField(label='Select a zip file', help_text='Max. 50 MB', widget=forms.ClearableFileInput(attrs={'multiple': True}))

JobChannalizedLearning/course/views.py
from django.shortcuts import render
from course.models import Catogaries, Course
# Create your views here.


def COURSES(request):
    catogery = Catogaries.objects.all()
    course = Course.objects.filter(status='PUBLISH').order_by('-id')
    context = {
        'catogery': catogery,
        'course': course,

    }
    return render(request, 'courses/course.html', context)


def course_detail(request, name):
    context = {}
    context['filtered_courses'] = Course.objects.filter(
        category=Catogaries.objects.get(name=name))
    return render(request, 'courses/filtered_course.html', context)


def filtered_content(request, name, slug):
    a = Course.objects.filter(slug=slug)
    context = {
        'a': a,
        'slug':slug
    }
    return render(request, 'courses/course_content.html', context)

JobChannalizedLearning/course/templates/courses/M_course.html
{% extends 'root.html' %} {% block content %}
<style>
  body {
    font-family: Arial, sans-serif;
  }

  .video-title {
    cursor: pointer;
    color: #007bff;
  }
</style>

<div class="container-fluid bg-light py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1 class="mb-4">Manage Content</h1>
      </div>
      <div class="col-md-4 text-md-end">
        <button
          id="add-course-button"
          data-bs-toggle="modal"
          data-bs-target="#addCategoryModal"
          class="btn btn-primary"
        >
          Add/Update Content
        </button>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-12">
        <h4>
          <a
            class="nav-link"
            href="{% url 'quiz:quizzes' slug=slug %}"
            style="color: blue"
            ><button class="btn btn-primary">Create Quiz</button>
          </a>
        </h4>
        <a class="nav-link" href="{% url 'website_content:course_view' slug %}"
          ><button class="btn btn-primary">Views</button></a
        >
      </div>
    </div>

    <div class="row row-cols-md-3 g-3 mt-4">
      {% for video in courses %}
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5
              class="card-title video-title"
              onclick="openModal('{{ video.video_file.url }}')"
            >
              {{ video.title }}
            </h5>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<!-- Video Modal -->
<div
  class="modal"
  id="videoModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
  style="max-width: 100px 700px"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <button
          type="button"
          class="close"
          onclick="closeModal()"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="embed-responsive embed-responsive-16by9">
          <video
            class="embed-responsive-item"
            controls
            id="modalVideo"
            style="width: 100%; height: 100%"
          >
            <source src="" type="video/mp4" />
          </video>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function openModal(videoSrc) {
    var modal = document.getElementById("videoModal");
    var modalVideo = modal.querySelector("#modalVideo");
    modalVideo.src = videoSrc;
    modal.style.display = "block";
  }

  function closeModal() {
    var modal = document.getElementById("videoModal");
    var modalVideo = modal.querySelector("#modalVideo");
    modalVideo.src = "";
    modal.style.display = "none";
  }
</script>

<!-- Add the following modal code -->
<div
  class="modal fade"
  id="addCategoryModal"
  tabindex="-1"
  aria-labelledby="addCategoryModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addCategoryModalLabel">
          Add/Update Content
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Include Bootstrap JS library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>

{% endblock%}

JobChannalizedLearning/course/templates/courses/M_filtered.html
{% extends 'root.html' %} {% block content %}

    <style>
        /* Additional custom CSS for responsive heading */
        @media (max-width: 768px) {
            .display-4 {
                font-size: 2rem;
            }
            
        }

        /* Adjust container margin */
        .container-margin {
            margin-top: 5px;
            margin-bottom: 5px; /* Added margin at the bottom to prevent container overflow */
        }
    </style>
</head>
<body>

{% comment %} Add New Course start {% endcomment %}

<div class="container mt-2" >
    <div class="m-4 p-2 rounded-3 shadow-lg  text-center mt-4" >
        <h1 class="display-4">Your Courses</h1>
        <p class="lead">Share your expertise with aspiring learners! Create and manage your courses on our platform.</p>
        <button id="add-course-button" class="btn btn-primary btn-lg mb-2" data-bs-toggle="modal" data-bs-target="#addCategoryModal">
            Add New Course
        </button>
    </div>
</div>

{% comment %} Add New Course end {% endcomment %}

{% comment %} Course card container start {% endcomment %}
<div class="container container-margin">
    <!-- Items -->
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 justify-content-center">
        {% for i in filtered_courses %}
        <div class="col pb-4">
            <!-- Card -->
            <div class="card h-100 border shadow-sm rounded-lg sk-fade">
                <!-- Image -->
                <div class="card-zoom position-relative">
                    <a href="{{ i.slug }}/" class="card-img sk-thumbnail img-ratio-1x1">
                        <img class="rounded shadow-light-lg img-fluid h-100 w-100" src="{{i.featured_image.url}}" alt="{{i.title}}">
                    </a>
                </div>

                <!-- Footer -->
                <div class="card-footer py-3 position-relative">
                    <a href="{{ i.slug }}/" class="d-block">
                        <!-- Link content -->
                    </a>

                    <!-- Preheading -->
                    <a href="{{ i.slug }}/">
                        <span class="mb-1 d-inline-block text-gray-800">{{i.category.name}}</span>
                    </a>

                    <!-- Heading -->
                    <div class="position-relative">
                        <a href="{{ i.slug }}/" class="d-block stretched-link">
                            <h4 class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2">{{i.title}}</h4>
                        </a>

                        <div class="d-flex align-items-end mb-2">
                            <div class="star-rating me-2">
                                <div class="rating" style="width: 50%"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% comment %} Course card container end {% endcomment %}

</body>



<div class="modal fade" id="addCategoryModal" tabindex="-1" aria-labelledby="addCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="addCategoryModalLabel">Add Course Content</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="d-grid mt-3">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Include Bootstrap JS library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


{% endblock %}

JobChannalizedLearning/course/templates/courses/course_content.html
{% extends 'root.html' %} {% block content %}
<style type=text/css>
  .btn-custom-size {
    /* Adjust the width and height as needed */
    width: 300px;
    height: 40px;
    /* Optionally, you can adjust other properties like font-size, padding, etc. */
    font-size: 16px;
    padding: 8px 16px;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Video List</h1>
      <div class="row">
        {% for video in courses %}
        <div class="col-md-4">
          <div class="card mb-3">
            <div class="card-body">
              <h5
                class="card-title video-title"
                onclick="openModal('{{ video.video_file.url }}')"
              >
                {{ video.title }}
              </h5>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-3">
      <div class="text-right" style="justify-content: space-evenly">
        {% if request.user.plan == 'Basic' %}
        <a href="{% url 'website_content:plan_details' %}"
          ><button id="add-course-button" class="btn btn-primary mb-4">
            Download Course Materials
          </button></a
        >
        {% else %}
        <button
          id="add-course-button"
          class="btn btn-primary mb-4 btn-custom-size"
          data-bs-toggle="modal"
          data-bs-target="#addCategoryModal"
        >
          Download Course Materials
        </button>
        {% endif %} {% if request.user.plan == 'Pro' %}
        <h6>
          <a
            class="btn btn-primary mb-4 btn-custom-size"
            href="{% url 'quiz:main-view' slug=slug %}"
            >Attempt Quiz
          </a>
        </h6>
        {% else %}
        <a href="{% url 'website_content:plan_details' %}"
          ><button id="add-course-button" class="btn btn-primary mb-4 btn-custom-size">
            Attempt Quiz
          </button></a
        >
        {% endif %}
        <!-- Add any additional functionalities or buttons here -->
      </div>
    </div>
  </div>
</div>

<!-- Video Modal -->
<div
  class="modal"
  id="videoModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
  style="max-width: 100px 700px"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <button
          type="button"
          class="close"
          onclick="closeModal()"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="embed-responsive embed-responsive-16by9">
          <video
            class="embed-responsive-item"
            controls
            id="modalVideo"
            style="width: 100%; height: 100%"
          >
            <source src="" type="video/mp4" />
          </video>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Add the following modal code -->
<div
  class="modal fade"
  id="addCategoryModal"
  tabindex="-1"
  aria-labelledby="addCategoryModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addCategoryModalLabel">Download Content</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="uploaded-file-link">
            <label for="{{ form.zip_file.id_for_label }}">File:</label>
            {% if form.zip_file.value %}
            <a href="/media/{{form.zip_file.value}}"
              >{{ form.zip_file.value }}</a
            >
            {% else %} No file selected. {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<style>
  /* Hide the form input element and checkbox */
  .uploaded-file-link input[type="file"],
  .uploaded-file-link input[type="checkbox"] {
    display: none;
  }
</style>

<script>
  function openModal(videoSrc) {
    var modal = document.getElementById("videoModal");
    var modalVideo = modal.querySelector("#modalVideo");
    modalVideo.src = videoSrc;
    modal.style.display = "block";
  }

  function closeModal() {
    var modal = document.getElementById("videoModal");
    var modalVideo = modal.querySelector("#modalVideo");
    modalVideo.src = "";
    modal.style.display = "none";
  }
</script>

{% endblock%}

JobChannalizedLearning/course/templates/courses/filtered_course.html
{% extends 'root.html' %} {% block content %}

<style>
  /* Additional custom CSS for responsive heading */
  @media (max-width: 768px) {
    .display-4 {
      font-size: 2rem;
    }
  }

  /* Adjust container margin */
  .container-margin {
    margin-top: 5px;
    margin-bottom: 5px; /* Added margin at the bottom to prevent container overflow */
  }
</style>

<body>
  <div class="container mt-2">
    <div class="m-4 p-2 rounded-3 shadow-lg text-center mt-4">
      <h1 class="display-4">Course Categories</h1>
      <p class="lead">
        Unlock your potential with online learning. Expand your mind and achieve
        your goals. A world of possibilities. Learn from the best with online
        courses.
      </p>
    </div>
  </div>

  <div
    class="m-4 tab-pane fade show active"
    id="pills-all"
    role="tabpanel"
    aria-labelledby="pills-all-tab"
  >
    <!-- Items -->
    <div class="mx-n2">
      <div class="row justify-content-center">
        <div
          class="d-flex justify-content-center row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-3"
        >
          {% for i in filtered_courses %}
          <div class="col pb-4">
            <!-- Card -->
            <div class="card h-100 border shadow-sm rounded-lg sk-fade">
              <!-- Image -->
              <a
                href="{{ i.slug }}/"
                class="card-img sk-thumbnail img-ratio-1x1"
              >
                <img
                  class="rounded shadow-light-lg img-fluid h-100 w-100"
                  src="{{i.featured_image.url}}"
                  alt="{{i.title}}"
                />
              </a>

              <!-- Footer -->
              <div class="card-footer py-3 position-relative">
                <a href="{{ i.slug }}/" class="d-block">
                  <!-- Preheading -->
                  <span class="mb-1 d-inline-block text-gray-800"
                    >{{i.category.name}}</span
                  >
                </a>

                <!-- Heading -->
                <div class="position-relative">
                  <a href="{{ i.slug }}/" class="d-block stretched-link">
                    <h4
                      class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2"
                    >
                      {{i.title}}
                    </h4>
                  </a>

                  <div class="d-flex align-items-end mb-2">
                    <div class="star-rating me-2">
                      <div class="rating" style="width: 50%"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}