JobChannalizedLearning/jcl/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from ApiApplication.views import FieldApiView as api_application_views, show_plot

urlpatterns = [
                  path('', include('user_account.urls')),
                  path('content/', include('website_content.urls')),
                  path('admin/', admin.site.urls),

                  # password Reset
                  path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                      template_name='registration/password_change_done.html'), name='password_change_done'),
                  path('password_change/',
                       auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
                       name='password_change'),
                  path('password_reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(),
                       name='password_reset'),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

                  # quiz section
                  path('quiz/', include('quiz.urls', namespace='quiz')),
                  path('dashboard/', show_plot, name='dashboard'),
                  re_path(r'fields', api_application_views.as_view()),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

JobChannalizedLearning/user_account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'user_account'
urlpatterns = [
    path('', views.user_login_view, name='login'),
    path('logout/', views.user_logout_view, name='logout'),
    path('you_have_to_logout_first/', views.you_have_to_logout_first, name='you_have_to_logout_first'),
    path('register/', views.user_registration_view, name='register'),
    path('login_first/', views.login_first, name='login_first'),
    path('registration_successful/', views.registration_successful_view, name='registration_successful'),
]

JobChannalizedLearning/website_content/urls.py
from django.urls import path, re_path
from .views import home_view, access_grades, course_view, course_detail, filtered_content, plan_details, pay, handle_transaction
from . import views


app_name = 'website_content'
urlpatterns = [
    path('home/', home_view, name='home'),
    path('home/<str:name>/', course_detail, name='course_detail'),
    path('home/<str:name>/<str:slug>/',
         filtered_content, name='filtered_content'),
    path('plan/', plan_details, name='plan_details'),
    path('pay/<str:price>/', pay, name='pay'),
    path('handle-transaction/<str:price>/',
         handle_transaction, name='handle_transaction'),
    path('access_grades/', access_grades, name='access_grades'),
    path('course/<slug:slug>/', course_view, name='course_view'),
]

JobChannalizedLearning/templates/snippets/admin.html
        <div>
        <h1>This is the Admin Page</h1>
            <p>please login as student or mentor to verify</p>
        </div>

JobChannalizedLearning/templates/snippets/footer.html
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
  integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
  integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
  crossorigin="anonymous"
></script>

<nav
  class="navbar  fixed-bottom  justify-content-center"
  style="background-color: #e0dcda;"
>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a
        class="nav-link disabled"
        style="color:black;"
      >
       JCL</a
      >
    </li>
  </ul>
</nav>

JobChannalizedLearning/templates/snippets/header.html
    <title>Job Channelized Learning </title>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top border-bottom-shadow-sm shadow-lg" style="background-color: #e0dcda;">
        {% if request.user.is_authenticated %}
        <div class="container-fluid d-flex">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link disabled" style="color: black;">Welcome {{ request.user.username }}</a></li>
            <li class="nav-item"><a class="nav-link" style="color: black" href={% url 'website_content:home' %}> Home</a></li>
            {% if request.user.user_role == 'STUDENT' %}
              <li class="nav-item"><a class="nav-link" style="color: black" href={% url 'website_content:plan_details' %}>⭐ Upgrade Plan</a></li>
              <li class="nav-item"><a class="nav-link"  style="color: black" href={% url 'dashboard' %}> Insights </a></li>
              {% elif request.user.user_role == 'MENTOR' %}
              <li class="nav-item"><a class="nav-link" style="color: black" href="{% url 'website_content:access_grades' %}">Student Grades</a></li>
            
            {% endif %}
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" style="color: black" href={% url 'user_account:logout' %}>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                  </svg>
                Logout</a></li>
          </ul>
        </div>

        {% else %}
        <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link disabled" style="color: black">Welcome</a>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" style="color: black" href={% url 'user_account:register' %}>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                  </svg>
                Register</a></li>
            <li class="nav-item"><a class="nav-link" style="color: black" href={% url 'user_account:login' %}>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                    <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                  </svg>
                Login</a></li>
          </ul>
        </div>
        {% endif %}
      </nav>

JobChannalizedLearning/templates/snippets/mentor.html
<div>
  <style>
    .text-shadow-1 {
      text-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.25);
    }

    .card-cover {
      background-repeat: no-repeat;
      background-position: center center;
      background-size: cover;
    }

    a {
      text-decoration: none;
    }
    .category-card:hover {
    transform: scale(1.02);
  }
  </style>

  <section class="pt-5 pb-9 py-md-11">
    <div class="container container-wd">
      <div class="row align-items-end mb-7">
        <div class="col-xl mb-5 mb-xl-0">
          <h1 class="mb-1">Categories</h1>
        </div>
        <div class="col-xl-auto">
          <!-- Nav -->
          <div
            class="nav justify-content-lg-start justify-content-xl-center justify-content-center tab-nav-1"
            id="pills-tab"
            role="tablist"
          >
            <button
              class="btn btn-primary"
              id="add-categories-button"
              data-bs-toggle="modal"
              data-bs-target="#addCategoryModal"
            >
              Add Categories
            </button>
          </div>
        </div>
      </div>
      <div class="container px-4 py-5" id="custom-cards">
        <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
          {% for course_type in catogery %}
          <div class="col category-card">
            <a href="{{ course_type.name }}/">
              <div
                class="card card-cover overflow-hidden text-bg-dark rounded-4"
                style="background-image: url('{{ course_type.category_image.url }}');"
              >
                <div
                  class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1"
                >
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">
                    {{ course_type.name }}
                  </h3>
                  <ul class="d-flex list-unstyled mt-auto"></ul>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
</div>

<!-- Add the following modal code -->
<div
  class="modal fade"
  id="addCategoryModal"
  tabindex="-1"
  aria-labelledby="addCategoryModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addCategoryModalLabel">Add Category</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body container mt-5 justify-content-center">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Add</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Include Bootstrap JS library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>

JobChannalizedLearning/templates/snippets/student.html
<div>
  <style>
    .text-shadow-1 {
      text-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.25);
    }
    .card-cover {
      background-repeat: no-repeat;
      background-position: center center;
      background-size: cover;
    }
    a {
      text-decoration: none;
    }
    .category-card:hover {
    transform: scale(1.02);
  }
  </style>
  <section class="pt-5 pb-9 py-md-11" style="fill: 100%">
    <div class="container container-wd">
      <div class="row align-items-end mb-7">
        <div class="col-xl mb-5 mb-xl-0">
          <h1
            class="mb-1"
            style="color: black; font-family: 'Al Bayan'; font-size: 40px"
          >
            Explore Featured Categories
          </h1>
          <p class="font-size-lg text-capitalize mb-0">
            Discover your perfect course in our categories.
          </p>
        </div>
      </div>
      <div class="container px-4 py-5" id="custom-cards">
        <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
          {% for course_type in catogery %}
          <div class="col category-card">
            <a href="{{ course_type.name }}/">
              <div
                class="card card-cover overflow-hidden text-bg-dark rounded-4"
                style="background-image: url('{{ course_type.category_image.url }}');"
              >
                <div
                  class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1"
                >
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">
                    {{ course_type.name }}
                  </h3>
                  <ul class="d-flex list-unstyled mt-auto"></ul>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
</div>