JobChannalizedLearning/course/urls.py
# course.urls.py
from django.urls import path
from .views import COURSES, course_detail, filtered_content


app_name = 'course'

urlpatterns = [
    # Updated name from 'Courses' to 'course_list'
    path('', COURSES, name='course_list'),
    path('<str:name>/', course_detail, name='course_detail'),
    path('<str:name>/<str:slug>/', filtered_content, name='filtered_content'),

]

JobChannalizedLearning/jcl/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from ApiApplication.views import FieldApiView as api_application_views, show_plot

urlpatterns = [
                  path('', include('user_account.urls')),
                  path('content/', include('website_content.urls')),
                  path('admin/', admin.site.urls),

                  # password Reset
                  path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                      template_name='registration/password_change_done.html'), name='password_change_done'),
                  path('password_change/',
                       auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
                       name='password_change'),
                  path('password_reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(),
                       name='password_reset'),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(
                           template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

                  # quiz section
                  path('quiz/', include('quiz.urls', namespace='quiz')),
                  path('dashboard/', show_plot, name='dashboard'),
                  re_path(r'fields', api_application_views.as_view()),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

JobChannalizedLearning/website_content/urls.py
from django.urls import path, re_path
from .views import home_view, access_grades, course_view, course_detail, filtered_content, plan_details, pay, handle_transaction
from . import views


app_name = 'website_content'
urlpatterns = [
    path('home/', home_view, name='home'),
    path('home/<str:name>/', course_detail, name='course_detail'),
    path('home/<str:name>/<str:slug>/',
         filtered_content, name='filtered_content'),
    path('plan/', plan_details, name='plan_details'),
    path('pay/<str:price>/', pay, name='pay'),
    path('handle-transaction/<str:price>/',
         handle_transaction, name='handle_transaction'),
    path('access_grades/', access_grades, name='access_grades'),
    path('course/<slug:slug>/', course_view, name='course_view'),
]

JobChannalizedLearning/course/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Catogaries(models.Model):
    name = models.CharField(max_length=200, null=True)
    category_image = models.ImageField(upload_to="course/", blank=True)

    def __str__(self):
        return(self.name)


class Course(models.Model):
    STATUS = (
        ('PUBLISH', 'PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )

    featured_image = models.ImageField(upload_to="featured_img/", blank=True)
    video_file = models.FileField(upload_to='videos/', null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    category = models.ForeignKey(Catogaries, on_delete=models.DO_NOTHING)
    description = models.TextField()
    zip_file = models.FileField(
        upload_to='zip_folders/', null=True, blank=True, default=None)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=100, null=True)
    author = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title


User = get_user_model()


class CourseView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    view = models.IntegerField(default=1)
    viewed_at = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"{self.user.username} viewed {self.course.title}"

JobChannalizedLearning/results/models.py
from django.db import models
from quiz.models import Quiz
from django.conf import settings

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

JobChannalizedLearning/website_content/models.py
from django.db import models

# Create your models here.

JobChannalizedLearning/course/forms.py
from django import forms
from course.models import Catogaries, Course

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Catogaries
        fields = ['name', 'category_image']

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['featured_image', 'video_file', 'zip_file','title', 'description', 'status']

# class ZipUploadForm(forms.Form):
#     zip_file = forms.FileField(label='Select a zip file', help_text='Max. 50 MB', widget=forms.ClearableFileInput(attrs={'multiple': True}))

JobChannalizedLearning/course/views.py
from django.shortcuts import render
from course.models import Catogaries, Course
# Create your views here.


def COURSES(request):
    catogery = Catogaries.objects.all()
    course = Course.objects.filter(status='PUBLISH').order_by('-id')
    context = {
        'catogery': catogery,
        'course': course,

    }
    return render(request, 'courses/course.html', context)


def course_detail(request, name):
    context = {}
    context['filtered_courses'] = Course.objects.filter(
        category=Catogaries.objects.get(name=name))
    return render(request, 'courses/filtered_course.html', context)


def filtered_content(request, name, slug):
    a = Course.objects.filter(slug=slug)
    context = {
        'a': a,
        'slug':slug
    }
    return render(request, 'courses/course_content.html', context)

JobChannalizedLearning/website_content/views.py
from django.shortcuts import render, redirect, get_object_or_404
from course.models import Catogaries, Course, CourseView
from quiz.models import Quiz
from results.models import Result
from course.forms import CategoryForm, CourseForm  # ZipUploadForm
import re
from django.conf import settings
from django.contrib.auth.decorators import login_required


# Create your views here.

def home_view(request):
    catogery = Catogaries.objects.all()
    course = Course.objects.filter(status='PUBLISH').order_by('-id')
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = CategoryForm()
    context = {
        'catogery': catogery,
        'course': course,
        'form': form
    }
    if not request.user.is_authenticated:
        return redirect('user_account:login_first')
    return render(request, 'website_content/home_page.html', context)


@login_required
def course_detail(request, name):
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            course_form = form.save(commit=False)
            course_form.author = request.user.username
            course_form.category = Catogaries.objects.get(name=name)
            slug = re.sub(r'[^\w\s]', '', form.cleaned_data['title']).lower()
            course_form.slug = re.sub(r'\s+', '_', slug)
            form.save()
    else:
        form = CourseForm()
    filtered_courses = Course.objects.filter(
        category=Catogaries.objects.get(name=name))
    context = {
        'filtered_courses': filtered_courses,
        'form': form
    }
    if request.user.user_role == 'STUDENT':
        return render(request, 'courses/filtered_course.html', context)
    else:
        filtered_courses = filtered_courses.filter(
            author=request.user.username)
        context['filtered_courses'] = filtered_courses
        return render(request, 'courses/M_filtered.html', context)

@login_required
def pay(request, price):
    return render(request, 'website_content/payment.html', {'price': price})

@login_required
def filtered_content(request, name, slug):
    courses = Course.objects.filter(slug=slug)
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES,
                          instance=courses.first())
        if form.is_valid():
            form.save()
    else:
        form = CourseForm(instance=courses.first())

    context = {
        'courses': courses,
        'form': form,
        'slug': slug,
    }

    if request.user.user_role == 'STUDENT':
        course = get_object_or_404(Course, slug=slug)
        course_view, created = CourseView.objects.get_or_create(
            user=request.user, course=course)
        if not created:
            course_view.view += 1
            course_view.save()
        return render(request, 'courses/course_content.html', context)
    else:
        return render(request, 'courses/M_course.html', context)


# membership pages
@login_required
def plan_details(request):
    return render(request, 'website_content/plans.html')


@login_required
def handle_transaction(request, price):
    print("inside handle")
    if price == '0':
        plan = 'Basic'
    elif price == '10':
        plan = 'Super'
    else:
        plan = 'Pro'
    user = request.user
    user.plan = plan
    user.save()
    return redirect('website_content:plan_details')

# Student grades


@login_required
def access_grades(request):
    courses = Course.objects.filter(author=request.user)
    course_slugs = courses.values_list('slug', flat=True)
    quizzes = Quiz.objects.filter(topic__in=course_slugs)
    results = Result.objects.filter(quiz__topic__in=course_slugs)

    context = {
        'courses': courses,
        'quizzes': quizzes,
        'results': results
    }
    return render(request, 'website_content/grades.html', context)


# views.py
@login_required
def course_view(request, slug):
    course = get_object_or_404(Course, slug=slug)
    course_views = CourseView.objects.filter(course=course).count()
    detail = CourseView.objects.filter(course=course)
    return render(request, 'website_content/course_view.html', {'course': course, 'course_views': course_views, 'detail': detail})

JobChannalizedLearning/templates/website_content/course_view.html
{% extends "root.html" %} {% block content %}

<div class="container bg-white">
  <h1 class="mt-5">{{ course.title }} Views</h1>
  <h5>Total Views: {{ course_views }}</h5>
  <div class="table-responsive">
    <table class="table table-bordered table-striped mt-4">
      <thead>
        <tr>
          <th>Student IDs</th>
          <th>Number of times viewed</th>
          <th>First Viewed At</th>
        </tr>
      </thead>
      <tbody>
        {% for d in detail %}
        <tr>
          <td>{{ d.user }}</td>
          <td>{{ d.view }}</td>
          <td>{{ d.viewed_at }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

JobChannalizedLearning/templates/website_content/grades.html
{% extends 'root.html' %} {% block content %}
<section class="bg-white p-4">
  <div>
    {% for course in courses %}
    <div class="card card-sm mb-4">
      <div class="card-header">
        <h1>{{ course.slug }}</h1>
      </div>
      <div class="card-body">
        {% for quiz in quizzes %} {% if course.slug in quiz.topic %}
        <div class="card mb-2">
          <div class="card-header">
            <h4>{{ quiz.name|slice:"3:" }}</h4>
          </div>
          <div class="card-body">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Student</th>
                  <th>Score</th>
                  <!-- Add more header columns if needed -->
                </tr>
              </thead>
              <tbody>
                {% for result in quiz.result_set.all %}
                <tr>
                  <td>{{ result.user }}</td>
                  <td>{{ result.score }}</td>
                  <!-- Display other result fields if needed -->
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% endif %} {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

JobChannalizedLearning/templates/website_content/home_page.html
{% extends 'root.html' %}
{% block content %}

    {% if request.user.user_role == 'STUDENT' %}
        {% include 'snippets/student.html' %}
    {% endif %}

    {% if request.user.user_role == 'MENTOR' %}
        {% include 'snippets/mentor.html' %}
    {% endif %}

    {% if request.user.user_role == 'ADMIN' %}
        {% include 'snippets/admin.html' %}
    {% endif %}

{% endblock content%} 

JobChannalizedLearning/templates/website_content/payment.html
<style>
  .w3-container {
    font-size: 14px;
  }

  .center {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }
</style>

<div class="center">
  <h3 class="donate">
    <div class="w3-card-4">
      <header class="w3-container w3-blue">
        <h1>Windsera</h1>
      </header>

      <div class="w3-container">
        <p>Make your Payment</p>

        <!-- PAYPAL BUTTONS HERE  -->

        <div id="paypal-button-container"></div>

        <!-- Include the PayPal JavaScript SDK -->
        <script src="https://www.paypal.com/sdk/js?client-id=AdVzw0rkUagzlmvfimuFFZkrsO8SzqD3OKOUXLrlCthx24lPx3E5coEamgONVhrcPwOPdtqYUTasqjh0&currency=USD&disable-funding=credit"></script>

        <script>
          // Render the PayPal button into #paypal-button-container
          paypal
            .Buttons({
              // Set up the transaction
              createOrder: function (data, actions) {
                return actions.order.create({
                  purchase_units: [
                    {
                      amount: {
                        value: "{{ price }}",
                      },
                    },
                  ],
                });
              },

              // Finalize the transaction
              onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                  // Redirect to the success page after successful payment
                  //window.location.href = "/handle-transaction/" + encodeURIComponent(details.purchase_units[0].amount.value) + "/";
                    window.location.href="{% url 'website_content:handle_transaction' price %}";
                });
              },
            })
            .render("#paypal-button-container");
        </script>
      </div>
    </div>
  </h3>
</div>

JobChannalizedLearning/templates/website_content/plans.html
{% extends 'root.html' %} {% block head %}
<title>Plan Selection</title>
<style>
  .plan-card {
    display: flex;
    flex-direction: column;
    justify-content: center;
    border: 1px solid #ccc;
    border-radius: 5px;
    padding: 20px;
    margin: 10px;
    text-align: center;
    background-color: #f8f8f8;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
  }

  .plan-card h3 {
    color: #333;
    margin-top: 0;
  }

  .plan-card p {
    color: #777;
  }

  .plan-card ul {
    list-style-type: none;
    padding: 0;
  }

  .plan-card li {
    margin-bottom: 10px;
  }

  .select-btn {
    background-color: #4caf50;
    color: white;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 10px 2px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .select-btn:hover {
    background-color: #45a049;
  }
</style>
{% endblock head %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <h2 class="text-center mt-4">
      Please Upgrade Your Plan To Enjoy Our Premium Features
    </h2>

    <div class="col-md-4">
      <div class="plan-card">
        <h3>Basic Plan</h3>
        <p>Features:</p>
        <ul>
          <li>Feature 1</li>
          <li>Feature 2</li>
          <li>Feature 3</li>
        </ul>
        {% if request.user.plan == 'Basic' %}
        <a class="select-btn">Selected</a>
        {% else %}
        <a
          href="{% url 'website_content:handle_transaction' 0 %}"
          class="select-btn"
          >Downgrade ☹️</a
        >
        {% endif %}
      </div>
    </div>

    <div class="col-md-4">
      <div class="plan-card">
        <h3>Super Plan</h3>
        <p>Features:</p>
        <ul>
          <li>Feature 1</li>
          <li>Feature 2</li>
          <li>Feature 3</li>
        </ul>
        {% if request.user.plan == 'Super' %}
        <a class="select-btn">Selected</a>
        {% elif request.user.plan == 'Basic' %}
        <a href="{% url 'website_content:pay' 10 %}" class="select-btn"
          >Upgrade 😃</a
        >
        {% else %}
        <a href="{% url 'website_content:pay' 10 %}" class="select-btn"
          >Downgrade ☹️</a
        >
        {% endif %}
      </div>
    </div>

    <div class="col-md-4">
      <div class="plan-card">
        <h3>Pro Plan</h3>
        <p>Features:</p>
        <ul>
          <li>Feature 1</li>
          <li>Feature 2</li>
          <li>Feature 3</li>
        </ul>
        {% if request.user.plan == 'Pro' %}
        <a class="select-btn">Selected</a>
        {% else %}
        <a href="{% url 'website_content:pay' 15 %}" class="select-btn"
          >Upgrade 😃</a
        >
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}